apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi
  labels:
    app: fastapi-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/fastapi
    argocd-image-updater.argoproj.io/image-update-strategy: name
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/allow-tags: '^[a-f0-9]{7,}$'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: 754874159206.dkr.ecr.ap-northeast-2.amazonaws.com/takeit/fastapi:4ddb544acc1c6576029e09f7692fcbaa2917801d
          ports:
            - containerPort: 8000
          env:
           - name: OPENAI_API_KEY
             valueFrom:
               secretKeyRef:
                 name: fastapi-secret
                 key: openai-api-key




                   
