name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set environment variables for OAuth
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Clone CD Repository
        env:
          PAT_TOKEN: ${{ secrets.CD_REPO_PAT }}
        run: |
          git clone https://$PAT_TOKEN@github.com/LGCNS-PJT-EDU/EDU_Deployment.git
          cd EDU_Deployment
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Update image tag in values.yaml
        run: |
          cd EDU_Deployment
          sed -i "s/^  tag: .*/  tag: \"${{ github.sha }}\"/" fastAPI/values.yaml

      - name: Commit and Push updated image tag
        run: |
          cd EDU_Deployment
          git add fastAPI/values.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push origin main